language: php
php:
- 5.5
- 5.6
install:
- composer install
env:
  global:
  - DB_HOST=localhost
  - DB_DATABASE=account_verification
  - DB_USERNAME=postgres
  - APP_ENV=testing
  - APP_KEY=rJhIZXkdo3FtwqdDJsC7Oad2HqhnarEE
  - TWILIO_ACCOUNT_SID=ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  - TWILIO_AUTH_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  - TWILIO_NUMBER=+15552737123
  - AUTHY_API_KEY=your_api_key
before_script:
  - psql -c 'create database account_verification;' -U postgres
  - php artisan migrate
